### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by pukuba** [pukuba/programmers-search#4]
- [x] 커뮤니티 로직 개발

- [x] for문 map, reduce로 변경가능한거 변경하기

- [x] Codeforces, Atcoder, Solved API 고려
